import { GameQuestion } from '@/types/types';

const categories = {
  ALCOOL: "🍺 Alcool & Soirées",
  BEFORE: "🎉 Before & After",
  CALIENTE: "🔥 Caliente",
  LIFE: "🌟 Life Story",
  CRUSH: "💘 Crush & Love",
  DARING: "😈 Daring & Wild"
};

// Fonction helper pour créer des questions avec une catégorie
const createQuestions = (category: string, questions: string[]): GameQuestion[] => {
  return questions.map(text => ({
    text: `Je n'ai jamais ${text}`,
    category,
    isChecked: false
  }));
};

// Questions par catégorie
const questions: GameQuestion[] = [
  // 🍺 Alcool & Soirées
  ...createQuestions(categories.ALCOOL, [
    // Classiques
    "bu avant midi",
    "mélangé plus de 5 alcools différents en une soirée",
    "bu directement à la bouteille en soirée",
    "fait un concours de shots",
    "joué à des jeux d'alcool toute une nuit",
    "bu un cocktail avec plus de 10 ingrédients",
    "fini une bouteille de vin en moins d'une heure",
    "bu dans un verre à shot plus grand que la normale",
    "participé à un beer pong en équipe mixte",
    "inventé un cocktail qui est devenu populaire",
    "fait une pyramide de verres qui s'est effondrée",
    "bu dans une chaussure",
    "fait un tour du monde des alcools en une soirée",
    "participé à un concours de qui tient le plus longtemps",
    "mélangé tous les alcools du bar dans un seul verre",
    
    // Situations
    "vomi dans un Uber après une soirée",
    "perdu mes clés/téléphone en soirée",
    "dormi dans la salle de bain",
    "fini une bouteille à moi tout seul",
    "dansé sur le bar",
    "été viré(e) d'un bar pour avoir trop dansé",
    "cassé un verre en essayant de trinquer trop fort",
    "renversé mon verre sur quelqu'un d'important",
    "confondu le verre de quelqu'un d'autre avec le mien",
    "fait tomber un plateau entier de shots",
    "commandé une tournée pour tout le bar",
    "été refusé(e) à l'entrée d'un bar car trop alcoolisé(e)",
    "perdu une chaussure en soirée",
    "fini la soirée dans le mauvais appartement",
    "réveillé tout l'immeuble en rentrant",
    
    // Conséquences
    "envoyé des messages que je regrette en étant bourré(e)",
    "appelé mon ex en étant saoul(e)",
    "posté des stories que j'ai supprimées le lendemain",
    "réveillé tous mes colocs en rentrant",
    "fait une déclaration d'amour sous l'effet de l'alcool",
    "acheté des choses en ligne en étant bourré(e)",
    "commandé assez de nourriture pour nourrir tout le quartier",
    "fait une promesse que je ne pouvais pas tenir",
    "révélé un secret que je devais garder",
    "perdu un pari stupide",
    "posté une story de moi en train de chanter à tue-tête",
    "envoyé un mail professionnel bourré(e)",
    "fait une demande en mariage improvisée",
    "adopté un animal en étant saoul(e)",
    "réservé des vacances sur un coup de tête",

    // Situations embarrassantes
    "confondu quelqu'un avec mon/ma pote en soirée",
    "embrassé la mauvaise personne en étant bourré(e)",
    "fait un strip-tease improvisé en soirée",
    "chanté à tue-tête dans la rue en rentrant",
    "fait une promesse que je ne me rappelle pas",
    "dansé sur une table qui s'est cassée",
    "embrassé mon reflet dans un miroir",
    "essayé de commander à un mannequin dans un magasin",
    "parlé à une plante pendant 10 minutes",
    "confondu un policier avec un videur",
    "fait un karaoké catastrophique devant tout le monde",
    "fait une déclaration d'amour à la mauvaise personne",
    "essayé de rentrer dans la mauvaise voiture",
    "appelé mon patron en pensant appeler ma mère",
    "fait un discours improvisé qui n'avait aucun sens",

    // Jeux d'alcool
    "perdu à 'Je n'ai jamais' et dû finir mon verre",
    "inventé une règle qui est devenue virale",
    "triché pendant un jeu à boire",
    "oublié les règles au milieu du jeu",
    "fait boire tout le monde en mentant",
    "participé à un beer pong en équipe avec mon ex",
    "gagné un concours de shots et regretté",
    "joué à la roulette russe avec des shots",
    "fait un flip cup qui a mal tourné",
    "organisé un tournoi de jeux d'alcool",
    "fait un ring of fire qui a duré toute la nuit",
    "joué à 'Ni oui ni non' en soirée",
    "perdu à pierre-feuille-ciseaux et dû boire",
    "fait un 'never have I ever' qui a créé des drames",
    "participé à un quiz alcoolisé",

    // Soirées mémorables
    "fini une soirée dans un pays différent",
    "participé à une soirée déguisée en mauvais costume",
    "fait une soirée dans un lieu improbable",
    "organisé une fête qui est devenue légendaire",
    "été à une soirée où la police est intervenue",
    "fait une soirée qui s'est terminée au petit déjeuner",
    "participé à une soirée surprise qui a mal tourné",
    "fait une soirée thématique qui a dérapé",
    "été à une soirée où quelqu'un a appelé les pompiers",
    "organisé une soirée qui a réuni des ennemis",
    "fait une soirée qui s'est transformée en karaoké géant",
    "participé à une soirée qui a fini en bataille d'eau",
    "été à une soirée où quelqu'un a fait une demande en mariage",
    "fait une soirée qui s'est terminée par un petit-déjeuner au restaurant",
    "organisé une soirée qui est devenue une tradition"
  ]),

  // 🎉 Before & After
  ...createQuestions(categories.BEFORE, [
    // Préparation
    "commencé à boire avant même d'arriver à la soirée",
    "changé de tenue 5 fois avant de sortir",
    "annulé au dernier moment pour rester Netflix",
    "invité des gens sans prévenir l'hôte",
    "fini la bouteille avant même le début de la soirée",
    "fait une sieste qui a duré trop longtemps",
    "acheté une tenue spéciale pour une soirée",
    "commencé à me préparer 5 heures avant",
    "fait une réunion stratégique pour la soirée",
    "créé une playlist spéciale soirée",
    "fait un pré-drinking tout seul",
    "organisé un before qui est devenu la vraie soirée",
    "fait les magasins en urgence avant la soirée",
    "emprunté des vêtements sans demander",
    "fait un maquillage qui a pris 2 heures",

    // Pendant la soirée
    "mixé de la musique sans rien y connaître",
    "fait une bataille de nourriture",
    "improvisé une chorégraphie collective",
    "organisé un karaoké improvisé",
    "transformé un dîner calme en grosse soirée",
    "changé la musique sans être le DJ",
    "fait une vidéo TikTok avec des inconnus",
    "créé un nouveau cocktail douteux",
    "lancé une bataille d'oreillers",
    "organisé un concours de danse improvisé",
    "fait un discours non prévu",
    "transformé le salon en piste de danse",
    "improvisé un jeu qui est devenu viral",
    "fait un live Instagram chaotique",
    "créé une nouvelle tradition de soirée",

    // After
    "ramené toute la soirée chez moi pour l'after",
    "commandé à manger à 4h du matin",
    "réveillé les voisins pendant l'after",
    "continué la fête jusqu'au petit déjeuner",
    "enchaîné directement avec le travail sans dormir",
    "fait un after dans un lieu improbable",
    "organisé un petit-déjeuner pour 20 personnes",
    "continué à danser jusqu'à midi",
    "fait un after qui est devenu une nouvelle soirée",
    "transformé mon appartement en hôtel improvisé",
    "fait un brunch qui s'est transformé en dîner",
    "créé un groupe WhatsApp spécial after",
    "fait un after qui a duré tout le week-end",
    "improvisé une pool party à l'after",
    "organisé un karaoké à 6h du matin",

    // Situations inattendues
    "perdu mon téléphone et retrouvé dans un endroit improbable",
    "rencontré quelqu'un de célèbre pendant l'after",
    "fini dans une ville différente",
    "participé à un mariage improvisé",
    "rejoint une fête d'inconnus",
    "créé une nouvelle amitié à 5h du matin",
    "fait un road trip spontané après la soirée",
    "organisé une chasse au trésor nocturne",
    "improvisé un concert dans la rue",
    "fait un after dans un fast-food",
    "participé à un tournage de film amateur",
    "créé un nouveau sport à 4h du matin",
    "fait un after dans une piscine",
    "organisé un défilé de mode improvisé",
    "fait un after qui s'est transformé en séance photo",

    // Conséquences du lendemain
    "manqué un rendez-vous important",
    "dormi toute la journée suivante",
    "perdu ma voix à force de chanter",
    "eu des courbatures pendant une semaine",
    "retrouvé des photos mystérieuses",
    "découvert des nouveaux amis sur Instagram",
    "reçu des messages de gens inconnus",
    "trouvé des objets mystérieux dans mes poches",
    "eu des flashbacks pendant des jours",
    "créé un groupe d'entraide pour survivre",
    "fait un debriefing qui a duré des heures",
    "découvert des vidéos embarrassantes",
    "eu des révélations existentielles",
    "fait des promesses impossibles à tenir",
    "planifié la prochaine soirée immédiatement"
  ]),

  // 🔥 Caliente
  ...createQuestions(categories.CALIENTE, [
    // Flirt
    "dragué plusieurs personnes dans la même soirée",
    "donné un faux numéro à quelqu'un",
    "embrassé plus de 3 personnes en une soirée",
    "fait croire que j'étais célibataire",
    "dansé de manière très suggestive avec un(e) inconnu(e)",
    "fait du pied à la mauvaise personne",
    "envoyé un message hot à la mauvaise personne",
    "flirté avec quelqu'un pour avoir un verre gratuit",
    "dragué le/la serveur(se)",
    "fait semblant d'être quelqu'un d'autre pour draguer",
    "utilisé une technique de drague ridicule",
    "fait croire que c'était mon anniversaire pour draguer",
    "inventé une vie complètement différente pour impressionner",
    "prétendu parler une autre langue",
    "fait semblant d'être un(e) célébrité",

    // Action ou Vérité version hot
    "fait un lap dance improvisé",
    "participé à un concours de bisous",
    "joué à 'je n'ai jamais' jusqu'à ce que ça devienne très hot",
    "relevé un défi osé en soirée",
    "participé à un jeu de strip",
    "fait un slow avec un(e) inconnu(e)",
    "participé à un concours de danse sensuelle",
    "joué à la bouteille avec des inconnus",
    "fait un body shot",
    "participé à un concours de t-shirt mouillé",
    "fait un massage à un(e) inconnu(e)",
    "joué à 'Twister' de manière suggestive",
    "participé à un speed dating sauvage",
    "fait un strip poker improvisé",
    "relevé un défi qui impliquait d'embrasser quelqu'un",

    // Situations chaudes
    "été surpris(e) dans une situation compromettante",
    "disparu mystérieusement pendant la soirée",
    "échangé des regards langoureux toute la soirée",
    "fini la soirée avec un(e) inconnu(e)",
    "eu un coup de foudre en soirée",
    "dansé sur une table pour séduire quelqu'un",
    "fait une démonstration de pole dance improvisée",
    "participé à un concours de qui embrasse le mieux",
    "fait une séance photo suggestive improvisée",
    "joué au/à la serveur(se) sexy",
    "fait un strip-tease sur une chanson ringarde",
    "improvisé une chorégraphie sensuelle",
    "fait semblant d'être mannequin lingerie",
    "participé à un défilé de maillots de bain improvisé",
    "fait une séance de photos boudoir improvisée",

    // Rencontres hot
    "embrassé quelqu'un dans un ascenseur",
    "eu un rendez-vous avec deux personnes le même jour",
    "flirté avec des jumeaux/jumelles",
    "dragué quelqu'un devant son ex",
    "embrassé le/la meilleur(e) ami(e) de mon ex",
    "eu un date dans un endroit très inapproprié",
    "fait croire que j'étais marié(e)",
    "inventé une histoire d'amour pour rendre jaloux",
    "fait semblant d'être en couple avec un(e) ami(e)",
    "organisé un rendez-vous surprise qui a mal tourné",
    "eu un crush sur un(e) professeur(e)",
    "dragué quelqu'un en utilisant une autre langue",
    "fait semblant d'être un sugar daddy/mama",
    "eu un date avec quelqu'un de célèbre",
    "participé à une émission de dating",

    // Fantasmes & Désirs
    "rêvé d'une personne interdite",
    "eu un crush sur une célébrité et stalké ses réseaux",
    "fantasmé sur quelqu'un d'inaccessible",
    "écrit une fanfiction érotique",
    "eu des pensées très hot pendant une réunion",
    "imaginé ma vie avec un(e) inconnu(e) croisé(e)",
    "créé un compte secret pour suivre mon crush",
    "collectionné des photos de mon crush",
    "fait des recherches poussées sur quelqu'un",
    "envoyé des messages anonymes à mon crush",
    "créé un faux profil pour espionner quelqu'un",
    "fait semblant de lire pour observer quelqu'un",
    "changé mes habitudes pour croiser quelqu'un",
    "rejoint un club juste pour voir quelqu'un",
    "appris une nouvelle langue pour impressionner"
  ]),

  // 🌟 Life Story
  ...createQuestions(categories.LIFE, [
    // Aventures
    "fait quelque chose d'illégal",
    "menti sur mon identité",
    "voyagé sans destination précise",
    "participé à une télé-réalité",
    "changé radicalement de vie sur un coup de tête",
    "déménagé dans un pays sans parler la langue",
    "participé à un flash mob",
    "fait du stop avec un(e) inconnu(e)",
    "dormi à la belle étoile dans un lieu interdit",
    "participé à une chasse au trésor géante",
    "fait un road trip sans planification",
    "rejoint un groupe de voyageurs inconnus",
    "participé à un festival sans billet",
    "fait du camping sauvage",
    "suivi un(e) inconnu(e) pour vivre une aventure",

    // Expériences
    "vécu une coïncidence incroyable",
    "rencontré une célébrité par hasard",
    "gagné un concours sans le vouloir",
    "eu une expérience paranormale",
    "vécu une histoire digne d'un film",
    "été témoin d'un événement historique",
    "survécu à une situation extrême",
    "fait une découverte importante par hasard",
    "vécu un moment de gloire inattendu",
    "été au mauvais endroit au bon moment",
    "vécu une histoire d'amour comme dans les films",
    "fait une rencontre qui a changé ma vie",
    "été impliqué(e) dans un événement viral",
    "vécu une expérience mystique",
    "été au centre d'une théorie du complot",

    // Confessions
    "gardé un secret pendant plus d'un an",
    "eu une double vie",
    "menti sur mon CV",
    "trahi la confiance de mon/ma meilleur(e) ami(e)",
    "caché quelque chose de grave à ma famille",
    "fait semblant d'être quelqu'un d'autre",
    "menti sur mes origines",
    "inventé une histoire pour impressionner",
    "caché une relation secrète",
    "fait croire que j'étais riche",
    "menti sur mon âge pendant longtemps",
    "inventé un talent que je n'avais pas",
    "fait semblant de connaître une célébrité",
    "menti sur mes voyages",
    "inventé une maladie pour avoir de l'attention",

    // Moments de folie
    "fait un tatouage sur un coup de tête",
    "changé de carrière du jour au lendemain",
    "vendu toutes mes possessions",
    "rejoint une communauté alternative",
    "participé à une manifestation spontanée",
    "créé un mouvement viral",
    "lancé une entreprise sans préparation",
    "organisé un événement qui a dépassé mes attentes",
    "fait une performance publique improvisée",
    "relevé un défi viral dangereux",
    "participé à un mariage surprise",
    "fait une intervention non préparée",
    "organisé un événement clandestin",
    "créé une œuvre d'art controversée",
    "lancé une mode improbable",

    // Révélations
    "découvert un secret de famille choquant",
    "appris une vérité qui a tout changé",
    "fait une découverte sur moi-même",
    "vécu une épiphanie en public",
    "réalisé que ma vie était basée sur un mensonge",
    "découvert un talent caché tardivement",
    "compris quelque chose d'évident très tard",
    "fait une révélation embarrassante",
    "avoué quelque chose de lourd à porter",
    "découvert une coïncidence troublante",
    "réalisé une prophétie par accident",
    "vécu un moment de clarté absolue",
    "fait une découverte qui a changé ma vision",
    "compris le sens de la vie pendant 5 minutes",
    "eu une révélation sous la douche"
  ]),

  // 💘 Crush & Love
  ...createQuestions(categories.CRUSH, [
    // Crush
    "eu le béguin pour le/la partenaire d'un(e) ami(e)",
    "stalké mon crush sur tous les réseaux",
    "fait semblant de croiser quelqu'un par hasard",
    "créé un faux compte pour espionner quelqu'un",
    "été obsédé(e) par quelqu'un pendant des mois",
    "changé mes habitudes pour croiser mon crush",
    "mémorisé l'emploi du temps de mon crush",
    "fait semblant d'aimer les mêmes choses que mon crush",
    "rejoint un club/cours juste pour mon crush",
    "demandé à des ami(e)s d'espionner mon crush",
    "fait des captures d'écran de tous les posts de mon crush",
    "analysé chaque emoji dans les messages de mon crush",
    "rêvé de mon crush plusieurs nuits de suite",
    "écrit notre futur nom de couple partout",
    "collectionné des objets liés à mon crush",

    // Relations
    "trompé quelqu'un",
    "été en couple avec deux personnes en même temps",
    "menti sur mon statut relationnel",
    "quitté quelqu'un par message",
    "bloqué mon ex sur tous les réseaux",
    "fait une scène de jalousie en public",
    "surveillé le téléphone de mon/ma partenaire",
    "fait semblant d'être en couple pour rendre jaloux",
    "menti sur mon passé amoureux",
    "gardé contact avec mon ex en secret",
    "organisé une rupture dramatique",
    "fait une déclaration d'amour qui a mal tourné",
    "été infidèle émotionnellement",
    "manipulé quelqu'un par amour",
    "fait du chantage affectif",

    // Techniques de séduction
    "utilisé une technique de drague d'un film",
    "inventé une histoire tragique pour séduire",
    "fait semblant d'être quelqu'un d'autre",
    "utilisé un faux accent pour draguer",
    "menti sur mon métier pour impressionner",
    "prétendu être ami(e) avec des célébrités",
    "inventé une relation passée avec quelqu'un de connu",
    "fait semblant d'être riche",
    "utilisé des photos retouchées sur les apps de rencontre",
    "menti sur mon âge pour séduire",
    "fait croire que j'étais célèbre",
    "inventé des voyages que je n'ai jamais faits",
    "prétendu avoir des talents particuliers",
    "fait semblant de parler plusieurs langues",
    "inventé un métier cool",

    // Situations amoureuses
    "fait une déclaration d'amour en public",
    "organisé une surprise romantique qui a mal tourné",
    "confondu le prénom de mon/ma partenaire",
    "oublié un anniversaire de relation",
    "fait une demande en mariage improvisée",
    "été largué(e) le jour de la Saint-Valentin",
    "fait une scène au mariage de mon ex",
    "envoyé un message d'amour à la mauvaise personne",
    "été pris(e) en train d'espionner mon ex",
    "stalké l'ex de mon/ma partenaire",
    "fait une crise de jalousie pour rien",
    "inventé une relation pour rendre jaloux",
    "organisé un rendez-vous catastrophique",
    "fait une déclaration d'amour sous l'effet de l'alcool",
    "confondu deux crush en même temps",

    // Amour toxique
    "harcelé mon ex sur les réseaux",
    "créé un faux compte pour surveiller mon/ma partenaire",
    "menti sur ma situation amoureuse",
    "manipulé quelqu'un pour qu'il/elle quitte son/sa partenaire",
    "saboté la relation d'un(e) ami(e)",
    "fait du chantage émotionnel",
    "utilisé une rupture pour obtenir quelque chose",
    "fait semblant d'être enceinte/d'avoir mis quelqu'un enceinte",
    "menacé de me faire du mal après une rupture",
    "répandu des rumeurs sur mon ex",
    "volé quelque chose à mon ex par vengeance",
    "contacté la famille de mon ex après la rupture",
    "utilisé des informations privées contre mon ex",
    "fait croire à une maladie grave pour garder quelqu'un",
    "menacé de révéler des secrets intimes"
  ]),

  // 😈 Daring & Wild
  ...createQuestions(categories.DARING, [
    // Défis
    "fait un saut en parachute",
    "participé à une course illégale",
    "fait du naturisme",
    "relevé un défi YouTube",
    "fait quelque chose d'extrême pour un pari",
    "mangé quelque chose de vraiment dégoûtant pour un défi",
    "fait un piercing/tatouage sur un coup de tête",
    "participé à un concours bizarre",
    "relevé un défi viral dangereux",
    "fait une cascade dangereuse",
    "participé à une expérience étrange",
    "testé une théorie du complot",
    "fait un défi alimentaire extrême",
    "relevé un défi physique intense",
    "participé à un jeu dangereux",

    // Folies
    "dépensé tout mon salaire en une soirée",
    "fait un tatouage sur un coup de tête",
    "changé de pays sans prévenir personne",
    "disparu pendant plusieurs jours",
    "fait quelque chose de complètement fou par amour",
    "acheté quelque chose de très cher impulsivement",
    "quitté mon travail sur un coup de tête",
    "fait une coloration capillaire extreme",
    "adopté un animal exotique",
    "investi toutes mes économies dans une crypto monnaie",
    "participé à un mariage surprise",
    "fait une modification corporelle extreme",
    "commencé une nouvelle vie sans prévenir",
    "rejoint une secte pendant quelques jours",
    "fait une folie qui m'a coûté très cher",

    // Aventures extrêmes
    "exploré un endroit abandonné la nuit",
    "fait de l'urbex dans un lieu dangereux",
    "nagé avec des requins",
    "fait de la plongée sans certification",
    "escaladé un bâtiment",
    "fait du ski hors-piste sans expérience",
    "conduit un véhicule sans permis",
    "fait du saut à l'élastique clandestin",
    "participé à une course poursuite",
    "fait de la spéléologie sans guide",
    "traversé une frontière illégalement",
    "fait du camping dans un lieu interdit",
    "participé à une expédition dangereuse",
    "fait de la moto à grande vitesse",
    "exploré des tunnels abandonnés",

    // Provocations
    "fait un scandale en public",
    "provoqué une bagarre",
    "fait une blague qui a mal tourné",
    "créé une polémique sur les réseaux",
    "fait une farce dangereuse",
    "participé à une manifestation illégale",
    "défié une figure d'autorité",
    "fait un canular qui a eu des conséquences",
    "provoqué un ex en public",
    "créé un buzz négatif volontairement",
    "fait une révélation choquante en public",
    "participé à un happening controversé",
    "fait une performance artistique provocante",
    "lancé une rumeur scandaleuse",
    "fait un prank qui a mal tourné",

    // Situations extrêmes
    "risqué ma vie pour une photo",
    "fait quelque chose d'illégal pour de l'argent",
    "participé à un pari dangereux",
    "testé mes limites physiques",
    "fait quelque chose de fou pour impressionner",
    "risqué mon travail pour une aventure",
    "participé à une expérience risquée",
    "fait quelque chose de dangereux en étant bourré(e)",
    "relevé un défi mortel",
    "fait quelque chose d'illégal par adrénaline",
    "participé à un événement underground",
    "fait une cascade sans protection",
    "testé une substance douteuse",
    "participé à un rituel étrange",
    "fait quelque chose qui aurait pu mal finir"
  ])
];

export { categories, questions as neverHaveIEverQuestions }; 